spring.application.name=biblioteca
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=guedes0410
spring.datasource.driver-class-name=org.postgresql.Driver

# Mostra o SQL no console
spring.jpa.show-sql=true

# Formata o SQL
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

jwt.expiration=${JWT_EXPIRATION:900000}
jwt.key=${JWT_KEY:FQ*X9Pwr&m\%OCM#~Ne[D3/q2+c4SzYRhA]<B!8,sK>_bng$=-Tp{ayV^:.?v5fZxWU6o(HJl0uLjd|ti}@GI71k)EGvLYoRzgplb2INk9FfC8PhqET1O6KSQd0ZBsxtuJymAaM37WjnVDUcew5irXH4}